### PR TITLE
Optimistic Modal for Deletions

### LINKED ISSUE #487: Instantly hide modal/popup on optimistic deletions
### Description

When a deletion is optimistic, we don't have to wait and close the modal when the server responds. Instead, we can optimistically close it.

### Acceptance Criteria

- Refactor `ConfirmModal` in order to be able to optimistically close
- Move snackbar pushes to the component that uses `ConfirmModal`
- Remove un-necessary "success" snackbars/toasters (the user can see that the item got deleted in front of him). If the item was not clear that it was deleted (since this particular UI didn't change), then we can keep the success snackbar

### PR DESCRIPTION
**Pull request by alexmylonas**
## Background

When a deletion is optimistic, we don't have to wait and close the modal when the server responds. Instead, we can optimistically close it.

Closes #487 

## Changes

- Added simplistic `ConfirmModal`
- Added `OptimisticModal` to close immediately after confirmation
- Updated `DeletePolicyModal` to use `OptimisticConfirmModal`
- Updated `DeleteRuleModal` to use `OptimisticConfirmModal`
- Updated `DeleteComplianceModal` to use `OptimisticConfirmModal`
- Updated `DeleteDestinationModal` to use `OptimisticConfirmModal`
- Updated `DeleteLogSourceModal` to use `OptimisticConfirmModal`
- Updated `DeleteUserModal` to use `OptimisticConfirmModal`

## Testing

- Locally

### CODE REVIEW

**Comment by alexmylonas** [comment]
@3nvi have a look and let me know!

**Comment by alexmylonas** [comment]
> Looks great! The only thing I don't undetstand is why we have a BaseConfirmModal. Shouldn't we delete it?

Currently, we are using it only on `ResetUserPasswordModal` which doesn't leverage optimistic response. Should I try to refactor this?

**Comment by 3nvi** [comment]
> > Looks great! The only thing I don't undetstand is why we have a BaseConfirmModal. Shouldn't we delete it?
> 
> Currently, we are using it only on `ResetUserPasswordModal` which doesn't leverage optimistic response. Should I try to refactor this?

`BaseConfirmModal` and `ConfirmModal` should be the same thing. 

You can either name the components:

* BaseConfirmModal
* BaseOptimisticConfirmModal

or

* ConfirmModal
* OptimisticConfirmModal

pick one of the two combos

**Comment by alexmylonas** [comment]
> You can either name the components:
> 
> * BaseConfirmModal
> * BaseOptimisticConfirmModal
> 
> or
> 
> * ConfirmModal
> * OptimisticConfirmModal
> 
> pick one of the two combos

Renamed BaseConfirmModal as ConfirmModal

**Pull request merged**
