### PR TITLE
Happy New Year

### PR DESCRIPTION
**Pull request by austinbyers**
## Background

Change `(c) 2020` to `(c) 2021` in license headers and email footers

## Changes

All of them. Interestingly, we almost have exactly 2021 source files

> 2,002 changed files with 2,022 additions and 2,018 deletions.

## Testing

`mage clean setup gen fmt test:ci`

### CODE REVIEW

**Comment by jacknagz** [comment]
@austinbyers you actually don't have to do this because Copyright is effective from the date forward in time

**Comment by austinbyers** [comment]
> @austinbyers you actually don't have to do this because Copyright is effective from the date forward in time

Sure, I know we don't have to. But most places do:

Screen Shot 2021-01-08 at 3 41 25 PM

Up to you

**Comment by jacknagz** [comment]
> > @austinbyers you actually don't have to do this because Copyright is effective from the date forward in time
> 
> Sure, I know we don't have to. But most places do:
> 
> Screen Shot 2021-01-08 at 3 41 25 PM
> 
> Up to you

I don't see a reason to

**Comment by austinbyers** [comment]
> I don't see a reason to

I think the reason is for new files. When we add _new_ code, it's probably not valid to say "(c) 2020" because those source files did not exist last year so we couldn't have had a copyright on them at the time.

An alternative to "(c) 2021" would be "(c) 2020-2021", for example

**Pull request closed without merging**
