### PR TITLE
Autogenerate S3 bucket names

### PR DESCRIPTION
**Pull request by austinbyers**
## Background
Fixes: #120

Panther currently creates five S3 buckets, which have names of the form "panther-(name)-(accountId)-(region)".  We chose this format because this is how AWS names default buckets: the accountId + region generally guarantee global uniqueness. However, there are security problems associated with a predictable name, especially one that includes an accountID (#120)

So what does an ideal bucket name look like?

- Must be globally unique (S3 is a global service)
- Must persist across deployments
- Should not leak any information about the account
- Should resist enumeration attacks (i.e. include randomness)

Fortunately, CloudFormation can autogenerate bucket names which satisfy all of the above requirements: `(stack)-(resource)-(random suffix)`

**This is a breaking change**, but we might as well do it now before v1. Existing deployments will have to start over or copy the data from the old to the new buckets.

## Changes

- Remove all `BucketName` properties - let CloudFormation name the buckets
    - Simplify resource names since they are part of the bucket name now
    - S3 access logs are still prefixed with accountID and region. This means access logs won't have the exact bucket name as a prefix, but it's still clear which bucket generated the logs.
- Fix `analysis-api` integration test (which has hardcoding bucket name)
    - Unrelated fix: always show output from integration tests

### Alternatives Considered
I considered using the [StackId pseudo parameter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-stackid), which is also random and persists across deployments. We could name buckets "(stackName)-(resourceName)-(stackId)", which would allow us to construct the bucket name for S3 access log prefixes as well, but then we would have to do string splitting to pull out just the UUID from the stack id/arn.

## Testing

- Deployed to dev account
- Signed in with a new user
- `mage test:integration`

Generated buckets:

Screen Shot 2020-02-10 at 2 56 35 PM

### CODE REVIEW

**Comment by rleighton** [comment]
Can you list some example names from your test deployments?

**Comment by austinbyers** [comment]
@nhakmiller one of the integration tests was hardcoding the bucket name (just pushed a fix for that), but I searched every other bucket prefix and couldn't find anything. Feel free to double check

@rleighton I updated the PR description with a screenshot of the generated buckets

**Comment by rleighton** [comment]
Do we want to do:
  (stack)-(region)-(resource)-(random suffix)
So they nicely group by region when listed? 

I'd like to avoid clicking around to find the bucket I care about. Folks will likely deploy this to multiple regions.

Thoughts?

**Comment by austinbyers** [comment]
> (stack)-(region)-(resource)-(random suffix)

The only difference between that and the default version is the addition of the region, right? You can sort buckets by region in the S3 console, I'm not sure that putting the region in the name adds much value. Uniqueness is still guaranteed across regions (I deployed to a separate region to verify)

To implement this suggestion, we would have to build the random suffix ourselves by string-splitting the stackID, something like:

```yaml
BucketName: !Sub
  - ${AWS::StackName}-mybucket-${AWS::Region}-${Suffix}
  - {Suffix: !Select [!Split [!Ref AWS::StackId, "/"], 2]}
```

This would generate names like `panther-buckets-source-us-east-1-51af3dc0-da77-11e4-872e-1234567db123`. That name is clearly too long, we could split it even further to get just some of the UUID:

```yaml
BucketName: !Sub
  - ${AWS::StackName}-mybucket-${AWS::Region}-${Suffix}
  - {Suffix: !Select [!Split [!Select [!Split [!Ref AWS::StackId, "/"], 2]], ":"], 3]}
```

to get `panther-buckets-source-us-east-1-1234567db123`, but this seems unnecessarily complex compared to just letting CloudFormation generate the name

**Comment by austinbyers** [comment]
> Folks will likely deploy this to multiple regions.

We as developers certainly will for testing, but why would the Panther application itself be in multiple regions?

**Comment by rleighton** [comment]
> > (stack)-(region)-(resource)-(random suffix)
> 
> The only difference between that and the default version is the addition of the region, right? You can sort buckets by region in the S3 console, I'm not sure that putting the region in the name adds much value. Uniqueness is still guaranteed across regions (I deployed to a separate region to verify)
> 
> To implement this suggestion, we would have to build the random suffix ourselves by string-splitting the stackID, something like:
> 
> ```yaml
> BucketName: !Sub
>   - ${AWS::StackName}-mybucket-${AWS::Region}-${Suffix}
>   - {Suffix: !Select [!Split [!Ref AWS::StackId, "/"], 2]}
> ```
> 
> This would generate names like `panther-buckets-source-us-east-1-51af3dc0-da77-11e4-872e-1234567db123`. That name is clearly too long, we could split it even further to get just some of the UUID:
> 
> ```yaml
> BucketName: !Sub
>   - ${AWS::StackName}-mybucket-${AWS::Region}-${Suffix}
>   - {Suffix: !Select [!Split [!Select [!Split [!Ref AWS::StackId, "/"], 2], ":"], 3]}
> ```
> 
> to get `panther-buckets-source-us-east-1-1234567db123`, but this seems unnecessarily complex compared to just letting CloudFormation generate the name

Yuk!  Nevermind!

**Comment by kostaspap** [comment]
> > Folks will likely deploy this to multiple regions.
> 
> We as developers certainly will for testing, but why would the Panther application itself be in multiple regions?

It quite possible that we will eventually offer multi-region or even purely regional setups. This will be really needed for the log-processing where cross-region data transport is pretty $$$ but also for redundancy.

**Comment by rleighton** [comment]
> > > Folks will likely deploy this to multiple regions.
> > 
> > 
> > We as developers certainly will for testing, but why would the Panther application itself be in multiple regions?
> 
> It quite possible that we will eventually offer multi-region or even purely regional setups. This will be really needed for the log-processing where cross-region data transport is pretty $$$ but also for redundancy. We don't do that now, but something to keep in mind nevertheless.

I fully expect most customers running in multiple regions with large log processing needs to do:
1. Deploy Panther in their closest region (compliance + log processing)
2. For every account/region NOT in 1 deploy Panther , but just enable log processing.

**Pull request merged**
