### PR TITLE
Feature Data Models

### PR DESCRIPTION
**Pull request by lindsey-w**
## Background

Merge feature branch 

## Changes

- new analysis type DataModels
- analysis api update to create/update/delete DataModels
- rules engine update to use datamodels for accessing events by common name
- new integration tests for analysis api updates
- new unit tests for enrichedevents in rules engine
- related PRs: #2004 , #2010 , #1945

## Testing

- `mage test:integration`
- `mage test:ci`

### CODE REVIEW

**Review by nhakmiller — APPROVED** [review]
🚢 full send 🚢

**Comment by jacknagz** [comment]
@lindsey-w why did we pin the aws-cfn-lint version? it's quite old and has some reported vulns by Snyk

**Comment by lindsey-w** [comment]
> @lindsey-w why did we pin the aws-cfn-lint version? it's quite old and has some reported vulns by Snyk

The newer version (1.10.0) caused a snyk check to fail when I pushed it up - but [it](https://app.snyk.io/org/jack.naglieri/project/28cc2ab5-cf6c-4c3b-901a-b86048306474/pr-check/b6e486a7-fb26-4ff7-b944-b168327a3195/license) was because of a license check.

**Comment by jacknagz** [comment]
@lindsey-w I think we should not pin old versions due to vulnerabilities. We can get around most license checks though because they are just CI dependencies

**Pull request merged**
