### PR TITLE
Improving stability when running rules

### LINKED ISSUE #460: Alerts should use default title and dedup string in case of an exception
### Description

In case the `title` or `dedup` Python methods fail, the event fails to match a rule. We should instead fallback to default values. 

### Acceptance Criteria

- If "title" method of a rule fails, fallback to default value
- If "dedup" method of a rule fails, fallback to default value

### PR DESCRIPTION
**Pull request by kostaspap**
## Background

Fixes #460 
In case title or dedup functions throw exception, we use default values instead of dropping event. 
This is meant to improve system stability and to make sure that no crucial events will be ignored. 

## Changes

- Switching to use default values for alert title and dedup string in case the dedup function or title function throw exception

## Testing

- Unit testing.

### CODE REVIEW

**Comment by kostaspap** [comment]
> How will users know if their dedup/title functions are throwing exceptions? Could we perhaps use the defaults to send an alert, but still set the status to exception? Does log processing normally create an alert if a rule body throws an exception, or just drops it?

Actually the rules don't have a "status" like policies have... if the `rule` method throws an exception, we log it and continue. We consider that the event didn't match a rule. 
Note that the event will still be stored in Athena (we store all events). But it will be considered that it didn't match the rule.

**Comment by nhakmiller** [comment]
> > How will users know if their dedup/title functions are throwing exceptions? Could we perhaps use the defaults to send an alert, but still set the status to exception? Does log processing normally create an alert if a rule body throws an exception, or just drops it?
> 
> Actually the rules don't have a "status" like policies have... if the `rule` method throws an exception, we log it and continue. We consider that the event didn't match a rule.
> Note that the event will still be stored in Athena (we store all events). But it will be considered that it didn't match the rule.

Hmm then it seems quite likely users will never know when their rules are throwing exceptions. Might be worth considering triggering an alert on exceptions in general then.

**Comment by kostaspap** [comment]
> > > How will users know if their dedup/title functions are throwing exceptions? Could we perhaps use the defaults to send an alert, but still set the status to exception? Does log processing normally create an alert if a rule body throws an exception, or just drops it?
> > 
> > 
> > Actually the rules don't have a "status" like policies have... if the `rule` method throws an exception, we log it and continue. We consider that the event didn't match a rule.
> > Note that the event will still be stored in Athena (we store all events). But it will be considered that it didn't match the rule.
> 
> Hmm then it seems quite likely users will never know when their rules are throwing exceptions. Might be worth considering triggering an alert on exceptions in general then.

When this happens we log at error level: https://github.com/panther-labs/panther/blob/83c6ed86044aa65e05a4e4f32895890a80c8c0bb/internal/log_analysis/rules_engine/src/engine.py#L51 . If this happens repeatedly a CW Alarm will trigger. That's the best mechanism we have right now. But we can definitely improve, I'm happy to hear suggestions :)

**Comment by nhakmiller** [comment]
> When this happens we log at error level:
> 
> https://github.com/panther-labs/panther/blob/83c6ed86044aa65e05a4e4f32895890a80c8c0bb/internal/log_analysis/rules_engine/src/engine.py#L51
> 
> . If this happens repeatedly a CW Alarm will trigger. That's the best mechanism we have right now. But we can definitely improve, I'm happy to hear suggestions :)

I think most users who are writing rules will not look at AWS to make sure the rules are working, if the issue is not displayed in the UI it will likely be missed for a long time. My suggestion is to still create an alert in the case of an exception, but with some indication that an exception was thrown during rule evaluation. Maybe even just replacing the dedup string/title with "An exception was thrown during rule evaluation".

Ideally this means a rule with an exception in it makes a lot of noise so that someone goes to look at it and fixes the exception.

**Pull request merged**
