### PR TITLE
Added onboarding docs link

### PR DESCRIPTION
**Pull request by nhakmiller**
## Background

Added a link in the onboarding workflow to direct users to the required steps for completing log source onboarding.

## Changes

- Added a link to the docs on log source onboarding page

## Testing

- `npm run start` and checked out the page from a local deployment

### CODE REVIEW

**Comment by nhakmiller** [comment]
Screen Shot 2020-04-28 at 3 30 28 PM

Hmm looks like we could use a new line there, let me see what I can do.

**Comment by nhakmiller** [comment]
Screen Shot 2020-04-28 at 3 34 17 PM

Looks a bit better now

**Comment by jacknagz** [comment]
It probably makes sense to adjust the first header to say `Allow Panther to Pull S3 Data`, and then create a second header above the text you added that says `Send Panther Notifications`

**Comment by nhakmiller** [comment]
> It probably makes sense to adjust the first header to say `Allow Panther to Read S3 Data`, and then create a second header above the text you added that says `Adding Notifications For New Data`

I'm afraid this may be a bit beyond my javascript skillz 😞 I can take a peak, but I might just let the frontend guys grab that one in their AM if they don't mind.

**Comment by alexmylonas** [comment]
Closing this in favor #786 !

**Pull request closed without merging**
