### PR TITLE
Change name of destination functions

### PR DESCRIPTION
**Pull request by kostaspap**
## Background

Changing name from `destination_overrides` to `destinations` according to this discussion: https://github.com/panther-labs/panther/pull/2165#discussion_r534324500

It seems that this feature was not released officially in 1.14, so we get some time to fix names like this

## Changes

- Updated name of method

## Testing

- mage test:python

### CODE REVIEW

**Review by wey-chiang — APPROVED** [review]
LGTM, we need to make sure the docs are updated properly to show the correct change in python syntax from `def destination_override` to `def destinations`. 

I'll update our docs internally on confluence

**Comment by wey-chiang** [comment]
What release are we aiming to include these changes in? @kostaspap

**Comment by kostaspap** [comment]
> What release are we aiming to include these changes in? @kostaspap

1.15!

**Comment by kostaspap** [comment]
> LGTM, we need to make sure the docs are updated properly to show the correct change in python syntax from `def destination_override` to `def destinations`.
> 
> I'll update our docs internally on confluence

Yup, will do!

**Pull request merged**
