### PR TITLE
Welcome to the Dark Side

### LINKED ISSUE #1013: Migrate OSS to dark theme
This epic involves keeping all UX the same and just changing all of our UI in order to use the new components and API introduced  by the new pounce version

### LINKED ISSUE #1017: Frontend: uncontrolled input warning
### Describe the bug

When adding a alert destination, there's a warning when checking the Severity Types.

This error is not isolated to a particular output destination, but most likely base form.

### Steps to reproduce

1. Go to Settings -> Destinations
2. Click on "+Add Destination"
3. Select any of the destinations
4. Check one of the "Severity Types"

### Expected behavior

No warnings in the console

### Environment
- Panther master

### Additional context

N/A

### PR DESCRIPTION
**Pull request by 3nvi**
## Background

Details of the background have been added [here](https://www.youtube.com/watch?v=-bzWSJG93P8)

This PR is too big and I couldn't split it into fewer files (due to it's an all or nothing thing). No functionality has been touched. Only UI. 

Closes  #1017 
Closes #1013 

## Changes

- Pounce has been updated to the latest dark theme palette
- All (literally ALL) pages and components have been updated, so they can use the new API of pounce, while also changing the palette and colors
- Split components logically
- Add basic animations
- Partly change the layout of some pages to account for the upcoming re-designs

## Testing

No functionality has been changed; only UI. Thus, I would find it extremely unlikely for something to have "broken". Testing was done **purely** visually

## Notes

If it's not  too much trouble, I would like everyone on the engineering team to devote 10 minutes to browse around this branch and just do their everyday tasks. I would like to know:

1) Did you see any UI that doesn't look right (i.e. have I forgot to update something)?
2) Do you find something annoying?

This PR **removes the UI freeze on OSS**, so people can start merging their PRs, while making sure to update the current branch until it gets merged.

## Screenshots

They are too many. I would have to take screenshots of  the entire app, butt here are some

Screen Shot 2020-06-27 at 12 37 49 PM
Screen Shot 2020-06-27 at 12 38 10 PM
Screen Shot 2020-06-27 at 12 38 30 PM
Screen Shot 2020-06-27 at 12 38 43 PM
Screen Shot 2020-06-27 at 12 38 53 PM
Screen Shot 2020-06-27 at 12 39 11 PM

### CODE REVIEW

**Comment by rleighton** [comment]
Can we remove the Log Analysis 'Overview' page until we have one? Have a place holder feels unprofessional.

**Comment by rleighton** [comment]
Strange vertical line in the editor (is this at 80 chars?) ... suggestion not having it.
image

**Comment by 3nvi** [comment]
> Can we remove the Log Analysis 'Overview' page until we have one? Have a place holder feels unprofessional.

I think we agreed that the "coming soon" was intentional. I remember us wanting to add  it after a meeting, but  I'm fully ok removing it if @jacknagz or @willow9886 agrees

**Comment by jacknagz** [comment]
> Can we remove the Log Analysis 'Overview' page until we have one? Have a place holder feels unprofessional.

Leave it - it actually is coming soon 😂

**Comment by jacknagz** [comment]
Feedback:

The last filter box should have a filler text of "Status" instead of "Enabled"

Screen Shot 2020-06-29 at 1 25 17 PM

* If possible, let's modify the hyperlink colors to better display with the dark background
* Reorganization of the list alerts page via @s0l0ist's changes
* Triggered Events => Events

**Comment by 3nvi** [comment]
> Strange vertical line in the editor (is this at 80 chars?) ... suggestion not having it.
> image

Gotcha. We had it before, but I've hidden it with CSS. Will remove

**Comment by 3nvi** [comment]
> * If possible, let's modify the hyperlink colors to better display with the dark background

I'll track it as a separate issue (already created) since changing it to white is not an option I currently like

**Comment by 3nvi** [comment]
> @3nvi AWESOME work, looks amazing.
> Some slight issues that i faced probably easy to fix.
> A couple Forms buttons never become available:
> 
> * Policy Creation
> * Rule Creation & Editing
> * Redacted secrets are required on destinations

Can't  replicate first two bullets. Are you sure you filled-in the mandatory fields?

**Pull request merged**
