### PR TITLE
[deployments] rename alb and sg

### PR DESCRIPTION
**Pull request by jacknagz**
## Background

To better identify Panther infra, we should make sure everything is prefixed with `panther-`. While analyzing the ALB logs, I noticed two components were not prefixed. 

## Changes

- Prefix the ALB and the SG

## Testing

- None

### CODE REVIEW

**Comment by 3nvi** [comment]
That naming must be related to template nesting. I'm sure that I've added `panther-XXX` in the past, but perhaps we thought it was un-needed for one reason or another. 

In any case, I agree with Austin that we need to test it first. I'm not 100% sure if the resource would be deleted, since the resource name remains the same, but we should check it

**Comment by austinbyers** [comment]
I tested this against an existing deployment (of 7fa37cc2). The security group name can be safely updated in place, but the load balancer cannot:

Screen Shot 2020-04-14 at 11 08 50 AM

We could work around this by manually removing/detaching the target groups, but then this will definitely destroy the existing load balancer. Unfortunately, I don't think changing the alb name is worth the developer and customer effort

**Comment by 3nvi** [comment]
> I tested this against an existing deployment (of [7fa37cc](https://github.com/panther-labs/panther/commit/7fa37cc2bba50d250a68e3970b4a214e4c294145)). The security group name can be safely updated in place, but the load balancer cannot:
> 
> Screen Shot 2020-04-14 at 11 08 50 AM
> 
> We could work around this by manually removing/detaching the target groups, but then this will definitely destroy the existing load balancer. Unfortunately, I don't think changing the alb name is worth the developer and customer effort

Even updating one (sec group) is better than nothing.

Since we are there, may I recommend to add proper panther [tags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-tags) to the resources? I don't know if "search by tags" is available, but it's still helpful for the user to understand that the "web" resource is associated to Panther by looking at the tags.

**Comment by austinbyers** [comment]
> Even updating one (sec group) is better than nothing.

Agreed, I'll just update the PR with that change and revert the other.

> Since we are there, may I recommend to add proper panther tags to the resources?

Tags are added automatically by CloudFormation when you deploy. We had "Application: Panther" tags to all resources as well as "Stack: (panther-cfn-stack-name)" See #443

**Pull request merged**
