### PR TITLE
[FE]: Compliance Source Additional configuration fields

### LINKED ISSUE #2335: [FE] Configurable Cloud Security Scanning
### Describe the ideal solution

The Cloud Security scanning system is fairly generic, and intended to work in most cases for the most uses. However, this sometimes falls apart for specific environments/use cases where these general assumptions are wrong.

Users should have more configuration options for Cloud Security scanning, similar to how Log Analysis has several configuration options (e.g. using KMS keys, using prefixes, using SQS/S3, etc). Specifically, we've had requests for the following configuration options:

- Specifying which regions should/should not be scanned to align with Organization SCPs that block all actions in certain regions
- Specifying which resource types should/should not be scanned for certain sources

These settings should be configurable when onboarding new sources.

### Related Services

source-api and snapshot scheduler/poller

### Designs

Designs will be shared here:
https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther/2334

### Acceptance Criteria

- When onboarding or editing a Cloud Security Source, the user should be able to:
  - Disable Cloud Security Scanning for certain AWS regions
     - A dropdown with all supported AWS regions where the user should be able to select which multiple regions to ignore
     - The disabled regions should be clearly indicated 
     - An info icon should read: "prevent Panther from scanning certain AWS regions"
  - Disable Cloud Security Scanning for certain Resource types
    - A dropdown with all resource types where the user should be able to select which resources to ignore
     - The disabled resources should be clearly indicated
     - An info icon should read: "prevent Panther from scanning certain Resource Types"

### PR DESCRIPTION
**Pull request by alexmylonas**
## Description

BE now supports the options for a compliance source to NOT scan specific regions and/or resource types.

The FE changes on this PR allows users to select regions and/or types they want to exclude from scanning on creating and on updating a compliance source.

Closes #2335 
### Design

Designs [here.](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/0d293ff7-a6c6-4ddc-9dd0-442c63b91995/commits/b61b921be3b17ee62e31623cc0c77f6eee24f17c/files/323d0ca1-81a8-40e7-83ee-0a05b870bb4a/layers/E41DFB1E-102D-4DDC-9EBB-1D8973CEE5C2?mode=build&selected=root-29B5633A-2CFB-46AA-AF4E-B1604603FFE3)

### Screencast

https://user-images.githubusercontent.com/14179917/106468192-47fc5500-64a6-11eb-86f3-1df6b9e5297f.mov

### Checklist:

- [x] Make sure you give a high-level overview of the problem & the solution
- [x] Make sure the related issue is referenced
- [x] Make sure screenshots are added if the UI is changed in any way
- [x] Make sure all of the significant logic is covered by tests
- [x] Make sure your changes are accessible (addition of aria-attributes & correct HTML semantics)
- [x] Make sure you reference the related design document if it exists
- [x] Make sure telemetry is added (analytics & errors)
- [ ] ~~Make sure the changes are responsive (appearing decently on devices)~~

### CODE REVIEW

**Comment by alexmylonas** [comment]
@wey-chiang There is an issue when **creating** a source with those new fields, although I am getting a valid response when creating the entry in DDB doesn't seem to store those new fields.

I am positive it's a BE issue. 

Note: When updating an existing source works as intended

**Review by vorillaz — APPROVED** [review]
🔥

**Review by wey-chiang — CHANGES_REQUESTED** [review]
I see the addition of the `regionIgnoreList` and `resourceTypeIgnoreList` fields but it appears that `resourceRegexIgnoreList` is missing

**Review by wey-chiang — COMMENTED** [review]
Removing the request changes so the process can be streamlined but the issue re: resourceRegexIgnoreList should be addressed

**Review by wey-chiang — APPROVED** [review]

**Pull request merged**
