### PR TITLE
Add all-contributors spec

### PR DESCRIPTION
**Pull request by 3nvi**
## Background

Add an easy way to manage people that have contributed to the platform

## Changes

- Update `CONTRIBUTING.MD`
- Add `.all-contributorsrc`

## Testing

N/A

### CODE REVIEW

**Comment by 3nvi** [comment]
@all-contributors please add @3nvi  for Code Documentation Design Bug and Infrastructure

**Comment by 3nvi** [comment]
@all-contributors please add @austinbyers  for Code Documentation Security Bug Infrastructure and Infrastructure

**Comment by 3nvi** [comment]
@all-contributors please add @nhakmiller  for Code Documentation Security Bug Infrastructure

**Comment by 3nvi** [comment]
@all-contributors please add @drixta  for Code

**Comment by 3nvi** [comment]
@all-contributors please add @alexmylonas   for Code and Bug

**Comment by 3nvi** [comment]
@all-contributors please add @sugandhalahoti   for Documentation

**Comment by 3nvi** [comment]
@all-contributors please add @kartikeypan  for  Documentation

**Comment by 3nvi** [comment]
@all-contributors please add @stoggi   for Code Security Infrastructure & Ideas

**Comment by 3nvi** [comment]
@all-contributors please add @jacknagz   for Code Documentation Security Content Ideas & ProjectManagement

**Comment by nhakmiller** [comment]
> @all-contributors please add @austinbyers for Code Documentation Security Bug Infrastructure and Infrastructure

You put infra twice here, and the bot also put in infra twice in the corresponding PR. Is that going to look weird?

**Comment by 3nvi** [comment]
> @all-contributors please add @austinbyers for Code Documentation Security Bug Infrastructure and Infrastructure

You are right. Gonna put up another PR and delete the one you mentioned

@all-contributors please add @austinbyers for Code Documentation Security Bug Infrastructure

**Pull request merged**
