### PR TITLE
Ignoring S3 files from unregistered sources

### PR DESCRIPTION
**Pull request by kostaspap**
## Background

Sometimes log processor will receive events from unregistered sources. This can happen if e.g. someone has configured bucket-wide SNS notifications but has registered only a subfolder in Panther. 

In those cases it doesn't make sense to fail and retry - just ignore the messages. 

## Changes

- If we receive messages from unregistered S3 path, log a warning and continue

## Testing

- Unit test

### CODE REVIEW

**Comment by rleighton** [comment]
Excellent idea.

**Review by rleighton — APPROVED** [review]
LGTM.

Note: this will still result in getting paged sometimes (when we get a bunch of warns at once). Still better than failing the batch.

**Comment by s0l0ist** [comment]
@kostaspap is this going to be synced to the release branch?

**Comment by kostaspap** [comment]
> @kostaspap is this going to be synced to the release branch?

This is [already](https://github.com/panther-labs/panther/commit/6566d2e43374abd9c5bdb9797b89d01986fac957) in the release branch. This PR was merged to master before the 1.12 branch was created.

**Pull request merged**
